### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by kawasakiairi** [kawasakiairi/gekikara#87]
# 概要
激辛食品専門のレビューサイト
ユーザーが食品を検索し、食品に対してレビューを投稿・閲覧できる機能を提供する。

## 各種情報
- [x] サービス名：ゲキカラ、ドウ？
- [x] サービスURL：https://gekikara-dou.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能 
- [x] マルチ検索
- [x] 検索結果一覧 閲覧
- [x] 食品詳細 閲覧
- [x] レビュー一覧 閲覧
- [x] レビュー詳細 閲覧
- [x] レビュー 投稿 / 編集 / 削除
- [x] ログイン / ログアウト
- [x] ユーザー 登録

## READMEレビュー時にMVPリリース時点で実装予定だったページ
- [x] トップページ
- [x] 検索結果一覧ページ
- [x] 食品詳細ページ（レビュー一覧含む）
- [x] レビュー詳細ページ
- [x] レビュー投稿ページ
- [x] レビュー編集ページ
- [x] ログインページ
- [x] ユーザー登録ページ
- [x] アプリ概要ページ

## READMEレビュー時から追加した機能
- [x] マイページ 閲覧
- [x] お気に入り食品 登録 / 解除

## サービスイメージがわかるようなスクリーンショット
| 機能 | 説明 | 画像 |
|------|------|------|
| マルチ検索 | 国、値段、食品カテゴリから食品を検索 | [![Image from Gyazo](https://i.gyazo.com/92ee2c3e03b9b0be2aac3d40c88bc7b1.png)](https://gyazo.com/92ee2c3e03b9b0be2aac3d40c88bc7b1) |
| 検索結果一覧 閲覧 | 検索条件に基づいた激辛食品一覧を表示 | [![Image from Gyazo](https://i.gyazo.com/74e688ec00ebe292d42e6934895dca4d.png)](https://gyazo.com/74e688ec00ebe292d42e6934895dca4d) |
| 食品詳細 閲覧 | 選択した激辛食品の詳細を表示 | [![Image from Gyazo](https://i.gyazo.com/8aa73903595ee400e8fb1c0ddded113a.png)](https://gyazo.com/8aa73903595ee400e8fb1c0ddded113a) |
| レビュー一覧 閲覧 | 選択した激辛食品の詳細を表示 | [![Image from Gyazo](https://i.gyazo.com/366023aab28a340e4ea21657684bbf9c.png)](https://gyazo.com/366023aab28a340e4ea21657684bbf9c) |
| レビュー 投稿 | 選択した激辛食品のレビューを投稿 | [![Image from Gyazo](https://i.gyazo.com/843d69af8d957368b90127f09506fa0a.png)](https://gyazo.com/843d69af8d957368b90127f09506fa0a) |
| ログイン / ログアウト | サイトへのログイン・ログアウト | [![Image from Gyazo](https://i.gyazo.com/3f7c4959272bd0490efb017112ac55da.png)](https://gyazo.com/3f7c4959272bd0490efb017112ac55da) |
| ユーザー登録 | サイトへのユーザー新規登録 | [![Image from Gyazo](https://i.gyazo.com/ba0f11aae71e8612bd8cbd1c66cd6f82.png)](https://gyazo.com/ba0f11aae71e8612bd8cbd1c66cd6f82) |
| マイページ | マイページの閲覧 | [![Image from Gyazo](https://i.gyazo.com/50fe9bc206fb1d3d6e01c2fd8759ebc6.png)](https://gyazo.com/50fe9bc206fb1d3d6e01c2fd8759ebc6) |

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
